### ISSUE TITLE
Cannot read property 'defaultLength' of undefined

### ISSUE THREAD

**Issue by zahorovskyi** [ransanjeev/react-date-input#2]
Hi. I have error when I press unsupported key (any key except "arrows", "tab", "backspace", "Delete").
![screenshot_9](https://user-images.githubusercontent.com/7338339/43791352-173f4868-9a7e-11e8-896a-91971ce7fcab.png)

Can you help me with it?

I found there is some problem inside DateInputComponent.prototype.onKeydown method with nextSection variable

**Comment by ransanjeev** [comment]
Closing this as per the above merge.
